CREATE DATABASE IF NOT EXISTS leadbot
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE leadbot;

SET NAMES utf8mb4;

DROP TABLE IF EXISTS operate_log;
DROP TABLE IF EXISTS rule_setting;
DROP TABLE IF EXISTS channel_setting;
DROP TABLE IF EXISTS team_member;
DROP TABLE IF EXISTS chat_message;
DROP TABLE IF EXISTS task_item;
DROP TABLE IF EXISTS follow_log;
DROP TABLE IF EXISTS lead;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    username VARCHAR(64) NOT NULL UNIQUE COMMENT '登录账号',
    password VARCHAR(255) NOT NULL COMMENT 'BCrypt 密码',
    name VARCHAR(64) NOT NULL COMMENT '用户姓名',
    role VARCHAR(32) NOT NULL COMMENT '角色：admin/manager/user',
    avatar VARCHAR(16) DEFAULT '' COMMENT '头像简写',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='系统用户表';

CREATE TABLE lead (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(128) NOT NULL COMMENT '客户姓名',
    company VARCHAR(255) NOT NULL COMMENT '公司名称',
    industry VARCHAR(128) DEFAULT '' COMMENT '行业',
    phone VARCHAR(64) DEFAULT '' COMMENT '联系方式',
    level VARCHAR(32) DEFAULT 'new' COMMENT '客户等级：high/follow/new',
    status VARCHAR(64) DEFAULT '新线索' COMMENT '客户状态',
    source VARCHAR(128) DEFAULT '' COMMENT '来源渠道',
    tags VARCHAR(1000) DEFAULT '' COMMENT '标签，逗号分隔',
    note VARCHAR(1000) DEFAULT '' COMMENT 'AI建议或备注',
    last_follow VARCHAR(128) DEFAULT '' COMMENT '最近跟进时间文案',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_lead_name (name),
    INDEX idx_lead_company (company),
    INDEX idx_lead_level (level),
    INDEX idx_lead_status (status)
) COMMENT='客户线索表';

CREATE TABLE follow_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    lead_id BIGINT NOT NULL COMMENT '客户ID',
    time VARCHAR(128) DEFAULT '' COMMENT '展示时间',
    title VARCHAR(255) NOT NULL COMMENT '日志标题',
    `desc` VARCHAR(2000) DEFAULT '' COMMENT '日志内容',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_follow_log_lead_id (lead_id)
) COMMENT='客户跟进记录表';

CREATE TABLE task_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    title VARCHAR(255) NOT NULL COMMENT '任务标题',
    `desc` VARCHAR(255) DEFAULT '' COMMENT '任务说明',
    done TINYINT(1) DEFAULT 0 COMMENT '是否完成',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='任务表';

CREATE TABLE chat_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    role VARCHAR(32) NOT NULL COMMENT '角色：user/bot',
    text VARCHAR(2000) NOT NULL COMMENT '消息内容',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='AI 聊天消息表';

CREATE TABLE team_member (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(64) NOT NULL COMMENT '成员姓名',
    role VARCHAR(64) NOT NULL COMMENT '岗位角色',
    leads INT DEFAULT 0 COMMENT '本周线索数',
    avatar VARCHAR(16) DEFAULT '' COMMENT '头像简写',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='团队成员表';

CREATE TABLE channel_setting (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(128) NOT NULL COMMENT '渠道名称',
    budget VARCHAR(255) DEFAULT '' COMMENT '预算说明',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='渠道投放配置表';

CREATE TABLE rule_setting (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    time_range VARCHAR(255) DEFAULT '' COMMENT '触达时间窗',
    follow_rule VARCHAR(1000) DEFAULT '' COMMENT '跟进规则',
    industry_rule VARCHAR(1000) DEFAULT '' COMMENT '行业规则',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='机器人规则配置表';

CREATE TABLE operate_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    module VARCHAR(64) NOT NULL COMMENT '模块名',
    action VARCHAR(64) NOT NULL COMMENT '操作类型',
    operator_name VARCHAR(64) DEFAULT '' COMMENT '操作人',
    detail VARCHAR(2000) DEFAULT '' COMMENT '操作详情',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_operate_module (module),
    INDEX idx_operate_action (action)
) COMMENT='操作日志表';
